spring:
  application:
    name: brief20
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update